id: DCF506CC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-08T11:58:55+00:00'
last_modified: '2022-05-30T04:53:43.288816+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    444d:
      image_group_id: I1PD95951
      title: གཏན་ཚིགས་ཀྱི་དེ་ཁོ་ན་ཉིད་བསྟན་པ།
      total_pages: 1054
      order: 106
      base_file: 444d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
