id: P8B668747
initial_creation_type: ocr
source_metadata:
  volumes:
    44415ac6802147a5bd2f098b98c57b60:
      base_file: v106.txt
      image_group_id: I1PD95951
      title: གཏན་ཚིགས་ཀྱི་དེ་ཁོ་ན་ཉིད་བསྟན་པ།
      total_pages: 1054
      volume_number: 106
